### ISSUE TITLE
error: function definition is not allowed here

### ISSUE THREAD

**Issue by edfink234** [SdtElectronics/cline#10] opened 2023-02-28 23:17 UTC
I tried to enter the following function 

```C++
void func(int x) noexcept(false)
{
    if (x > 10)
    {
        throw 1;	
    }
}
```
but it gives the error in the title of this issue:

```
Compilation error:
input_line_11:3:1: error: function definition is not allowed here
{
^
```

**Comment by SdtElectronics** [comment] 2023-03-01 00:32
Seems to be a bug in Cling. I can reproduce this in ROOT 6.24/06, and the Cling used by the Cline in service was build upon https://github.com/root-project/cling/commit/1d5536fd0bc1ed3d3cedcd98d78e77208d772602. No related commits were found in the upstream after that, so presumably the problem is still there. I reported it at https://github.com/root-project/cling/issues/490 and I'll keep this issue open till it is confirmed by the Cling maintainers.

**Comment by SdtElectronics** [comment] 2023-03-03 02:44
Closing as problem has been confirmed from the upstream. See https://github.com/root-project/root/pull/11265 for updates.

**Closed as completed by SdtElectronics** 2023-03-03 02:44 UTC
